services:
  shorty:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: production
    env_file: .env
    # Run a command against the development stage of the image
    command: npm start
    ports:
      - 3000:3000
    networks:
      - backend_network
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shorty
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge   